name: GitHub Bump Flow

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout..."
        uses: actions/checkout@v3     
      - name: "Bumping Version..."
        run: ls
      - run: git config user.email ${{ secrets.G_EMAIL }}
      - run: git config user.name ${{ secrets.G_AUTHOR }}
      - run: npm version patch
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION}
      - run: git push "https://${{secrets.G_ACTOR}}:$GITHUB_TOKEN@github.com/${{secrets.G_ACTOR}}/Advance-Console.git" --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_BUMPER }}
      - run: git push "https://${{secrets.G_ACTOR}}:$GITHUB_TOKEN@github.com/${{secrets.G_ACTOR}}/Advance-Console.git" --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_BUMPER }}
          
  trigger:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - name: "Triggering..."
        uses: convictional/trigger-workflow-and-wait@v1.6.0
        with:
          owner: ${{ secrets.G_AUTHOR }}
          repo: "Advance-Console"
          github_token: ${{secrets.GIT_BUMPER}}
          workflow_file_name: gitpublish.yml
