name: GitHub Publish Flow

on:
  workflow_dispatch
#   push:
#     branches:
#       - main

jobs:
  publish-github:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout..."
        uses: actions/checkout@v3      
      - name: "Node Server..."
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/      
      - name: "Pulling Yarn..."
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: "Pipeline Job 1..."
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Creating Package Bundle... $VERSION"
          yarn build
          echo "Switching Directory > Build..."
          cd build
          echo "Publishing To GitHub..."
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GIT_TOKEN}}
          
  publish-npmjs:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout..."
        uses: actions/checkout@v3      
      - name: "Node Server..."
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: "Pulling Yarn..."
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install
          
      - name: "Pipeline Job 2..."
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Creating Package Bundle... $VERSION"
          yarn build
          echo "Switching Directory > Build..."
          cd build
          echo "Publishing To NPMJS..."
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}        
  
